// place for action types
export const SAVE_RECIPES_START = 'SAVE_RECIPES';
export const SAVE_RECIPES_SUCCESS = 'SAVE_RECIPES_SUCCESS';
export const SAVE_RECIPES_FAIL = 'SAVE_RECIPES_FAIL';
export const ADD_TO_FAVORITE ='ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
export const LOADING_RECIPES = 'LOADING_RECIPES';
